import Foundation
import Security

class KeychainService {
    static let shared = KeychainService()
    private init() {}

    enum KeychainError: LocalizedError {
        case saveFailed(OSStatus)
        case passwordDataInvalid

        var errorDescription: String? {
            switch self {
            case .saveFailed(let status):
                let msg = SecCopyErrorMessageString(status, nil) as String? ?? "Unknown"
                return "Keychain error (\(status)): \(msg)"
            case .passwordDataInvalid:
                return "Password could not be encoded."
            }
        }
    }

    func save(website: String, username: String, password: String) throws {
        guard let passwordData = password.data(using: .utf8) else {
            throw KeychainError.passwordDataInvalid
        }

        let server = normalise(website)

        // kSecAttrSynchronizable = true syncs to iCloud Keychain
        // so it appears in the Apple Passwords app on all your devices.
        let addQuery: [String: Any] = [
            kSecClass as String:               kSecClassInternetPassword,
            kSecAttrServer as String:          server,
            kSecAttrAccount as String:         username,
            kSecValueData as String:           passwordData,
            kSecAttrLabel as String:           website.isEmpty ? "Burner Account" : website,
            kSecAttrComment as String:         "Generated by BurnerMail",
            kSecAttrSynchronizable as String:  kCFBooleanTrue as Any
        ]

        let status = SecItemAdd(addQuery as CFDictionary, nil)
        NSLog("BurnerMail keychain add status: \(status)")

        switch status {
        case errSecSuccess:
            return

        case errSecDuplicateItem:
            let searchQuery: [String: Any] = [
                kSecClass as String:              kSecClassInternetPassword,
                kSecAttrServer as String:         server,
                kSecAttrAccount as String:        username,
                kSecAttrSynchronizable as String: kCFBooleanTrue as Any
            ]
            let updateAttrs: [String: Any] = [kSecValueData as String: passwordData]
            let updateStatus = SecItemUpdate(searchQuery as CFDictionary, updateAttrs as CFDictionary)
            if updateStatus != errSecSuccess {
                throw KeychainError.saveFailed(updateStatus)
            }

        default:
            throw KeychainError.saveFailed(status)
        }
    }

    private func normalise(_ input: String) -> String {
        var s = input.trimmingCharacters(in: .whitespacesAndNewlines).lowercased()
        s = s.replacingOccurrences(of: "https://", with: "")
        s = s.replacingOccurrences(of: "http://", with: "")
        s = s.replacingOccurrences(of: "www.", with: "")
        if let slash = s.firstIndex(of: "/") { s = String(s[..<slash]) }
        return s.isEmpty ? "burner-account" : s
    }
}
