import Foundation
import Security

class KeychainService {
    static let shared = KeychainService()
    private init() {}

    enum KeychainError: LocalizedError {
        case saveFailed(OSStatus)
        case passwordDataInvalid

        var errorDescription: String? {
            switch self {
            case .saveFailed(let status):
                let msg = SecCopyErrorMessageString(status, nil) as String? ?? "Unknown"
                return "Keychain error (\(status)): \(msg)"
            case .passwordDataInvalid:
                return "Password could not be encoded."
            }
        }
    }

    func save(website: String, username: String, password: String) throws {
        guard let passwordData = password.data(using: .utf8) else {
            throw KeychainError.passwordDataInvalid
        }

        let server = normalise(website)
        let label  = website.isEmpty ? "Burner Account" : website

        // Try first with iCloud Keychain sync enabled. This makes the entry show
        // up in the Apple Passwords app across all the user's signed-in devices.
        // Sync requires the app to be code-signed with a Developer Team and the
        // iCloud Keychain entitlement. If that's missing the keychain returns
        // -34018 (errSecMissingEntitlement); in that case we fall back to a
        // local-only save which still shows in the Passwords app on this Mac.
        do {
            try add(server: server, username: username, password: passwordData,
                    label: label, synchronizable: true)
        } catch KeychainError.saveFailed(let status) where isMissingEntitlement(status) {
            NSLog("BurnerMail: keychain sync entitlement unavailable (\(status)), retrying local-only")
            try add(server: server, username: username, password: passwordData,
                    label: label, synchronizable: false)
        }
    }

    // MARK: - Private

    private func add(server: String,
                     username: String,
                     password: Data,
                     label: String,
                     synchronizable: Bool) throws {

        var addQuery: [String: Any] = [
            kSecClass as String:        kSecClassInternetPassword,
            kSecAttrServer as String:   server,
            kSecAttrAccount as String:  username,
            kSecValueData as String:    password,
            kSecAttrLabel as String:    label,
            kSecAttrComment as String:  "Generated by BurnerMail"
        ]
        if synchronizable {
            addQuery[kSecAttrSynchronizable as String] = kCFBooleanTrue as Any
        }

        let status = SecItemAdd(addQuery as CFDictionary, nil)
        NSLog("BurnerMail keychain add status: \(status) (sync=\(synchronizable))")

        switch status {
        case errSecSuccess:
            return

        case errSecDuplicateItem:
            var searchQuery: [String: Any] = [
                kSecClass as String:       kSecClassInternetPassword,
                kSecAttrServer as String:  server,
                kSecAttrAccount as String: username
            ]
            if synchronizable {
                searchQuery[kSecAttrSynchronizable as String] = kCFBooleanTrue as Any
            }
            let updateAttrs: [String: Any] = [kSecValueData as String: password]
            let updateStatus = SecItemUpdate(searchQuery as CFDictionary,
                                             updateAttrs as CFDictionary)
            if updateStatus != errSecSuccess {
                throw KeychainError.saveFailed(updateStatus)
            }

        default:
            throw KeychainError.saveFailed(status)
        }
    }

    /// errSecMissingEntitlement (-34018) and a couple of related statuses that
    /// surface when an app isn't signed with the iCloud Keychain entitlement.
    private func isMissingEntitlement(_ status: OSStatus) -> Bool {
        switch status {
        case errSecMissingEntitlement: return true   // -34018
        case -25243:                   return true   // errSecNoAccessForItem (rare)
        default:                       return false
        }
    }

    private func normalise(_ input: String) -> String {
        var s = input.trimmingCharacters(in: .whitespacesAndNewlines).lowercased()
        s = s.replacingOccurrences(of: "https://", with: "")
        s = s.replacingOccurrences(of: "http://", with: "")
        s = s.replacingOccurrences(of: "www.", with: "")
        if let slash = s.firstIndex(of: "/") { s = String(s[..<slash]) }
        return s.isEmpty ? "burner-account" : s
    }
}
